### ISSUE TITLE
Add timestamps

### ISSUE THREAD

**Issue by vipul0425** [vipul0425/Calorie-Tracker#2]
Add timestamps when users add a meal to track the timing of the meal.

**Comment by RaviTejaVattem** [comment]
Shall I work on this??

If so what date format are you expecting??

Is the following date and formatting okay for you??

![image](https://user-images.githubusercontent.com/43704759/135727727-605a9620-6a35-4b54-931e-c226dab28b22.png)

**Comment by Aravind22** [comment]
have given a PR for the issue

**Comment by vipul0425** [comment]
yes, @RaviTejaVattem go to go, if you can then Just change the color of the date or time or change its font style so one can easily distinguish between-meal, calories, and time.

**Comment by RaviTejaVattem** [comment]
Sure, Thank you

**Comment by vipul0425** [comment]
And please make sure to Open PR in the contributions branch.
